### ISSUE TITLE
[Operations] New operation requests from User Study

### ISSUE THREAD

**Issue by qiaw99** [DFKI-NLP/InterroLang#115]
- [ ] least important feature (globaltopk only) #122 
- [x] least frequent keyword #116 
- [ ] include + similar (see comment below)
- [ ] custom input rationale #117 
- [ ] buttons for include operations #122
